# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleProducts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleProducts
  pod 'RxSwift', '6.0.0'
  pod 'RxRelay', '6.0.0'
  pod 'RxCocoa', '6.0.0'

  target 'SampleProductsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleProductsUITests' do
    # Pods for testing
  end

end
