# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MovieBooster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieBooster
  pod 'RxSwift', '6.2.0'
  pod 'RxRelay', '6.2.0'

  target 'MovieBoosterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieBoosterUITests' do
    # Pods for testing
  end

end
